/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ecevlsi.nsut.ac.in)
#  Generated on:      Wed Jul  1 12:54:02 2026
#  Design:            spi_top
#  Command:           write_netlist /home/ece82/spi_project/results/spi_final_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 25 2026 12:32:08 IST (Jun 25 2026 07:02:08 UTC)
// Verification Directory fv/spi_top 
module spi_top (
	clk, 
	rst_n, 
	start, 
	master_tx, 
	master_rx, 
	master_done, 
	master_busy, 
	slave_tx, 
	slave_rx, 
	slave_data_valid);
   input clk;
   input rst_n;
   input start;
   input [7:0] master_tx;
   output [7:0] master_rx;
   output master_done;
   output master_busy;
   input [7:0] slave_tx;
   output [7:0] slave_rx;
   output slave_data_valid;

   // Internal wires
   wire FE_PHN4_sclk;
   wire FE_PHN3_u_spi_master_div_cnt_0;
   wire FE_PHN2_u_spi_slave_sclk_d1;
   wire FE_PHN1_u_spi_slave_cs_n_d1;
   wire FE_PHN0_cs_n;
   wire [3:0] u_spi_slave_bit_cnt;
   wire [7:0] u_spi_slave_tx_shift_reg;
   wire [3:0] u_spi_master_bit_cnt;
   wire [7:0] u_spi_master_tx_shift_reg;
   wire [2:0] u_spi_master_state;
   wire [7:0] u_spi_master_rx_shift_reg;
   wire [7:0] u_spi_slave_rx_shift_reg;
   wire [1:0] u_spi_master_div_cnt;
   wire cs_n;
   wire miso;
   wire mosi;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire sclk;
   wire u_spi_master_sclk_en;
   wire u_spi_slave_cs_n_d1;
   wire u_spi_slave_cs_n_d2;
   wire u_spi_slave_sclk_d1;
   wire u_spi_slave_sclk_d2;

   CLKBUFX2 FE_PHC4_sclk (.A(sclk),
	.Y(FE_PHN4_sclk));
   CLKBUFX2 FE_PHC3_u_spi_master_div_cnt_0 (.A(u_spi_master_div_cnt[0]),
	.Y(FE_PHN3_u_spi_master_div_cnt_0));
   CLKBUFX2 FE_PHC2_u_spi_slave_sclk_d1 (.A(u_spi_slave_sclk_d1),
	.Y(FE_PHN2_u_spi_slave_sclk_d1));
   CLKBUFX2 FE_PHC1_u_spi_slave_cs_n_d1 (.A(u_spi_slave_cs_n_d1),
	.Y(FE_PHN1_u_spi_slave_cs_n_d1));
   CLKBUFX2 FE_PHC0_cs_n (.A(cs_n),
	.Y(FE_PHN0_cs_n));
   DFFSHQX1 \u_spi_slave_bit_cnt_reg[2]  (.CK(clk),
	.D(n_72),
	.Q(u_spi_slave_bit_cnt[2]),
	.SN(rst_n));
   DFFSHQX1 \u_spi_slave_bit_cnt_reg[1]  (.CK(clk),
	.D(n_73),
	.Q(u_spi_slave_bit_cnt[1]),
	.SN(rst_n));
   DFFRHQX1 u_spi_slave_miso_reg (.CK(clk),
	.D(n_69),
	.Q(miso),
	.RN(rst_n));
   OAI211X1 g2615__2398 (.A0(n_61),
	.A1(n_65),
	.B0(n_70),
	.C0(n_71),
	.Y(n_73));
   OAI2BB1XL g2607__5107 (.A0N(u_spi_slave_bit_cnt[2]),
	.A1N(n_71),
	.B0(n_70),
	.Y(n_72));
   SDFFRHQX1 u_spi_master_mosi_reg (.CK(clk),
	.D(n_15),
	.Q(mosi),
	.RN(rst_n),
	.SE(n_49),
	.SI(mosi));
   DFFSHQX1 \u_spi_slave_bit_cnt_reg[0]  (.CK(clk),
	.D(n_66),
	.Q(u_spi_slave_bit_cnt[0]),
	.SN(rst_n));
   OAI21X1 g2623__6260 (.A0(n_36),
	.A1(n_45),
	.B0(n_30),
	.Y(n_69));
   DFFRHQX1 \u_spi_slave_tx_shift_reg_reg[3]  (.CK(clk),
	.D(n_58),
	.Q(u_spi_slave_tx_shift_reg[3]),
	.RN(rst_n));
   DFFRHQX1 \u_spi_slave_tx_shift_reg_reg[1]  (.CK(clk),
	.D(n_64),
	.Q(u_spi_slave_tx_shift_reg[1]),
	.RN(rst_n));
   DFFSHQX1 \u_spi_master_bit_cnt_reg[1]  (.CK(clk),
	.D(n_62),
	.Q(u_spi_master_bit_cnt[1]),
	.SN(rst_n));
   DFFRHQX1 \u_spi_slave_tx_shift_reg_reg[6]  (.CK(clk),
	.D(n_57),
	.Q(u_spi_slave_tx_shift_reg[6]),
	.RN(rst_n));
   DFFRHQX1 \u_spi_slave_tx_shift_reg_reg[5]  (.CK(clk),
	.D(n_60),
	.Q(u_spi_slave_tx_shift_reg[5]),
	.RN(rst_n));
   DFFRHQX1 \u_spi_slave_tx_shift_reg_reg[4]  (.CK(clk),
	.D(n_59),
	.Q(u_spi_slave_tx_shift_reg[4]),
	.RN(rst_n));
   DFFRHQX1 \u_spi_slave_tx_shift_reg_reg[2]  (.CK(clk),
	.D(n_63),
	.Q(u_spi_slave_tx_shift_reg[2]),
	.RN(rst_n));
   SDFFRHQX1 \u_spi_master_tx_shift_reg_reg[0]  (.CK(clk),
	.D(u_spi_master_tx_shift_reg[0]),
	.Q(u_spi_master_tx_shift_reg[0]),
	.RN(rst_n),
	.SE(n_68),
	.SI(n_11));
   SDFFRHQX1 \u_spi_master_tx_shift_reg_reg[6]  (.CK(clk),
	.D(u_spi_master_tx_shift_reg[6]),
	.Q(u_spi_master_tx_shift_reg[6]),
	.RN(rst_n),
	.SE(n_68),
	.SI(n_21));
   SDFFRHQX1 \u_spi_master_tx_shift_reg_reg[2]  (.CK(clk),
	.D(u_spi_master_tx_shift_reg[2]),
	.Q(u_spi_master_tx_shift_reg[2]),
	.RN(rst_n),
	.SE(n_68),
	.SI(n_26));
   SDFFSHQX1 \u_spi_master_bit_cnt_reg[2]  (.CK(clk),
	.D(u_spi_master_bit_cnt[2]),
	.Q(u_spi_master_bit_cnt[2]),
	.SE(n_67),
	.SI(n_16),
	.SN(rst_n));
   SDFFSHQX1 \u_spi_master_bit_cnt_reg[0]  (.CK(clk),
	.D(u_spi_master_bit_cnt[0]),
	.Q(u_spi_master_bit_cnt[0]),
	.SE(n_67),
	.SI(n_8),
	.SN(rst_n));
   NAND3BX1 g2633__4319 (.AN(n_65),
	.B(n_70),
	.C(n_44),
	.Y(n_66));
   SDFFRHQX1 \u_spi_master_tx_shift_reg_reg[5]  (.CK(clk),
	.D(u_spi_master_tx_shift_reg[5]),
	.Q(u_spi_master_tx_shift_reg[5]),
	.RN(rst_n),
	.SE(n_68),
	.SI(n_19));
   SDFFRHQX1 \u_spi_master_tx_shift_reg_reg[4]  (.CK(clk),
	.D(u_spi_master_tx_shift_reg[4]),
	.Q(u_spi_master_tx_shift_reg[4]),
	.RN(rst_n),
	.SE(n_68),
	.SI(n_20));
   SDFFRHQX1 \u_spi_master_tx_shift_reg_reg[1]  (.CK(clk),
	.D(u_spi_master_tx_shift_reg[1]),
	.Q(u_spi_master_tx_shift_reg[1]),
	.RN(rst_n),
	.SE(n_68),
	.SI(n_25));
   DFFRHQX1 \u_spi_slave_tx_shift_reg_reg[0]  (.CK(clk),
	.D(n_46),
	.Q(u_spi_slave_tx_shift_reg[0]),
	.RN(rst_n));
   SDFFRHQX1 \u_spi_master_tx_shift_reg_reg[3]  (.CK(clk),
	.D(u_spi_master_tx_shift_reg[3]),
	.Q(u_spi_master_tx_shift_reg[3]),
	.RN(rst_n),
	.SE(n_68),
	.SI(n_22));
   INVXL g2644 (.A(n_55),
	.Y(n_64));
   INVXL g2643 (.A(n_51),
	.Y(n_63));
   MXI2XL g2622__8428 (.A(n_1),
	.B(n_27),
	.S0(n_67),
	.Y(n_62));
   NAND2XL g2648__5526 (.A(n_61),
	.B(n_65),
	.Y(n_71));
   INVXL g2653 (.A(n_47),
	.Y(n_60));
   INVXL g2652 (.A(n_50),
	.Y(n_59));
   INVXL g2651 (.A(n_56),
	.Y(n_58));
   INVXL g2654 (.A(n_48),
	.Y(n_57));
   AOI222XL g2655__6783 (.A0(u_spi_slave_tx_shift_reg[2]),
	.A1(n_54),
	.B0(n_53),
	.B1(slave_tx[3]),
	.C0(n_52),
	.C1(u_spi_slave_tx_shift_reg[3]),
	.Y(n_56));
   AOI222XL g2646__3680 (.A0(u_spi_slave_tx_shift_reg[0]),
	.A1(n_54),
	.B0(n_53),
	.B1(slave_tx[1]),
	.C0(n_52),
	.C1(u_spi_slave_tx_shift_reg[1]),
	.Y(n_55));
   AOI222XL g2645__1617 (.A0(u_spi_slave_tx_shift_reg[1]),
	.A1(n_54),
	.B0(n_53),
	.B1(slave_tx[2]),
	.C0(n_52),
	.C1(u_spi_slave_tx_shift_reg[2]),
	.Y(n_51));
   AOI222XL g2656__2802 (.A0(u_spi_slave_tx_shift_reg[3]),
	.A1(n_54),
	.B0(n_53),
	.B1(slave_tx[4]),
	.C0(n_52),
	.C1(u_spi_slave_tx_shift_reg[4]),
	.Y(n_50));
   NOR2XL g2635__1705 (.A(n_43),
	.B(n_67),
	.Y(n_49));
   AOI222XL g2658__5122 (.A0(u_spi_slave_tx_shift_reg[5]),
	.A1(n_54),
	.B0(n_53),
	.B1(slave_tx[6]),
	.C0(n_52),
	.C1(u_spi_slave_tx_shift_reg[6]),
	.Y(n_48));
   AOI222XL g2657__8246 (.A0(u_spi_slave_tx_shift_reg[4]),
	.A1(n_54),
	.B0(n_53),
	.B1(slave_tx[5]),
	.C0(n_52),
	.C1(u_spi_slave_tx_shift_reg[5]),
	.Y(n_47));
   AO22XL g2660__7098 (.A0(u_spi_slave_tx_shift_reg[0]),
	.A1(n_52),
	.B0(n_53),
	.B1(slave_tx[0]),
	.Y(n_46));
   AOI22X1 g2659__6131 (.A0(miso),
	.A1(n_52),
	.B0(u_spi_slave_tx_shift_reg[6]),
	.B1(n_54),
	.Y(n_45));
   NAND2XL g2667__1881 (.A(u_spi_slave_bit_cnt[0]),
	.B(n_52),
	.Y(n_44));
   NOR2XL g2672__5115 (.A(u_spi_slave_bit_cnt[0]),
	.B(n_52),
	.Y(n_65));
   DFFRHQX1 \u_spi_master_state_reg[0]  (.CK(clk),
	.D(n_39),
	.Q(u_spi_master_state[0]),
	.RN(rst_n));
   SDFFSHQX1 u_spi_master_cs_n_reg (.CK(clk),
	.D(n_31),
	.Q(cs_n),
	.SE(n_42),
	.SI(cs_n),
	.SN(rst_n));
   SDFFRHQX1 u_spi_master_sclk_en_reg (.CK(clk),
	.D(n_43),
	.Q(u_spi_master_sclk_en),
	.RN(rst_n),
	.SE(n_42),
	.SI(u_spi_master_sclk_en));
   SDFFRHQX1 u_spi_master_sclk_reg (.CK(clk),
	.D(sclk),
	.Q(sclk),
	.RN(rst_n),
	.SE(n_33),
	.SI(n_14));
   SDFFRHQX1 \u_spi_master_rx_shift_reg_reg[7]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[7]),
	.Q(u_spi_master_rx_shift_reg[7]),
	.RN(rst_n),
	.SE(n_41),
	.SI(u_spi_master_rx_shift_reg[6]));
   SDFFRHQX1 \u_spi_master_rx_shift_reg_reg[6]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[6]),
	.Q(u_spi_master_rx_shift_reg[6]),
	.RN(rst_n),
	.SE(n_41),
	.SI(u_spi_master_rx_shift_reg[5]));
   SDFFRHQX1 \u_spi_master_rx_shift_reg_reg[4]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[4]),
	.Q(u_spi_master_rx_shift_reg[4]),
	.RN(rst_n),
	.SE(n_41),
	.SI(u_spi_master_rx_shift_reg[3]));
   SDFFRHQX1 \u_spi_master_rx_shift_reg_reg[0]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[0]),
	.Q(u_spi_master_rx_shift_reg[0]),
	.RN(rst_n),
	.SE(n_41),
	.SI(miso));
   NAND2XL g2649__7482 (.A(n_32),
	.B(n_40),
	.Y(n_67));
   SDFFRHQX1 \u_spi_master_rx_shift_reg_reg[2]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[2]),
	.Q(u_spi_master_rx_shift_reg[2]),
	.RN(rst_n),
	.SE(n_41),
	.SI(u_spi_master_rx_shift_reg[1]));
   SDFFRHQX1 \u_spi_master_rx_shift_reg_reg[5]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[5]),
	.Q(u_spi_master_rx_shift_reg[5]),
	.RN(rst_n),
	.SE(n_41),
	.SI(u_spi_master_rx_shift_reg[4]));
   SDFFRHQX1 \u_spi_master_rx_shift_reg_reg[1]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[1]),
	.Q(u_spi_master_rx_shift_reg[1]),
	.RN(rst_n),
	.SE(n_41),
	.SI(u_spi_master_rx_shift_reg[0]));
   SDFFRHQX1 \u_spi_master_rx_shift_reg_reg[3]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[3]),
	.Q(u_spi_master_rx_shift_reg[3]),
	.RN(rst_n),
	.SE(n_41),
	.SI(u_spi_master_rx_shift_reg[2]));
   NAND2XL g2650__4733 (.A(n_38),
	.B(n_40),
	.Y(n_68));
   OAI21X1 g2647__6161 (.A0(n_34),
	.A1(n_35),
	.B0(n_38),
	.Y(n_39));
   SDFFRHQX1 \u_spi_slave_rx_shift_reg_reg[7]  (.CK(clk),
	.D(u_spi_slave_rx_shift_reg[7]),
	.Q(u_spi_slave_rx_shift_reg[7]),
	.RN(rst_n),
	.SE(n_37),
	.SI(u_spi_slave_rx_shift_reg[6]));
   SDFFRHQX1 \u_spi_slave_rx_shift_reg_reg[3]  (.CK(clk),
	.D(u_spi_slave_rx_shift_reg[3]),
	.Q(u_spi_slave_rx_shift_reg[3]),
	.RN(rst_n),
	.SE(n_37),
	.SI(u_spi_slave_rx_shift_reg[2]));
   SDFFRHQX1 \u_spi_slave_rx_shift_reg_reg[2]  (.CK(clk),
	.D(u_spi_slave_rx_shift_reg[2]),
	.Q(u_spi_slave_rx_shift_reg[2]),
	.RN(rst_n),
	.SE(n_37),
	.SI(u_spi_slave_rx_shift_reg[1]));
   NOR2XL g2685__9315 (.A(n_53),
	.B(n_54),
	.Y(n_52));
   SDFFRHQX2 u_spi_master_busy_reg (.CK(clk),
	.D(master_busy),
	.Q(master_busy),
	.RN(rst_n),
	.SE(n_6),
	.SI(n_18));
   SDFFRHQX1 \u_spi_slave_rx_shift_reg_reg[4]  (.CK(clk),
	.D(u_spi_slave_rx_shift_reg[4]),
	.Q(u_spi_slave_rx_shift_reg[4]),
	.RN(rst_n),
	.SE(n_37),
	.SI(u_spi_slave_rx_shift_reg[3]));
   SDFFRHQX1 \u_spi_slave_rx_shift_reg_reg[0]  (.CK(clk),
	.D(u_spi_slave_rx_shift_reg[0]),
	.Q(u_spi_slave_rx_shift_reg[0]),
	.RN(rst_n),
	.SE(n_37),
	.SI(mosi));
   SDFFRHQX1 \u_spi_slave_rx_shift_reg_reg[6]  (.CK(clk),
	.D(u_spi_slave_rx_shift_reg[6]),
	.Q(u_spi_slave_rx_shift_reg[6]),
	.RN(rst_n),
	.SE(n_37),
	.SI(u_spi_slave_rx_shift_reg[5]));
   SDFFRHQX1 \u_spi_slave_rx_shift_reg_reg[5]  (.CK(clk),
	.D(u_spi_slave_rx_shift_reg[5]),
	.Q(u_spi_slave_rx_shift_reg[5]),
	.RN(rst_n),
	.SE(n_37),
	.SI(u_spi_slave_rx_shift_reg[4]));
   SDFFRHQX1 \u_spi_slave_rx_shift_reg_reg[1]  (.CK(clk),
	.D(u_spi_slave_rx_shift_reg[1]),
	.Q(u_spi_slave_rx_shift_reg[1]),
	.RN(rst_n),
	.SE(n_37),
	.SI(u_spi_slave_rx_shift_reg[0]));
   SDFFRHQX2 \u_spi_slave_rx_data_reg[7]  (.CK(clk),
	.D(slave_rx[7]),
	.Q(slave_rx[7]),
	.RN(rst_n),
	.SE(n_36),
	.SI(u_spi_slave_rx_shift_reg[7]));
   SDFFRHQX2 \u_spi_slave_rx_data_reg[4]  (.CK(clk),
	.D(slave_rx[4]),
	.Q(slave_rx[4]),
	.RN(rst_n),
	.SE(n_36),
	.SI(u_spi_slave_rx_shift_reg[4]));
   NAND2BX1 g2668__9945 (.AN(n_35),
	.B(n_34),
	.Y(n_40));
   SDFFRHQX2 \u_spi_slave_rx_data_reg[0]  (.CK(clk),
	.D(slave_rx[0]),
	.Q(slave_rx[0]),
	.RN(rst_n),
	.SE(n_36),
	.SI(u_spi_slave_rx_shift_reg[0]));
   SDFFRHQX2 \u_spi_slave_rx_data_reg[3]  (.CK(clk),
	.D(slave_rx[3]),
	.Q(slave_rx[3]),
	.RN(rst_n),
	.SE(n_36),
	.SI(u_spi_slave_rx_shift_reg[3]));
   SDFFRHQX2 \u_spi_slave_rx_data_reg[2]  (.CK(clk),
	.D(slave_rx[2]),
	.Q(slave_rx[2]),
	.RN(rst_n),
	.SE(n_36),
	.SI(u_spi_slave_rx_shift_reg[2]));
   SDFFRHQX2 \u_spi_slave_rx_data_reg[1]  (.CK(clk),
	.D(slave_rx[1]),
	.Q(slave_rx[1]),
	.RN(rst_n),
	.SE(n_36),
	.SI(u_spi_slave_rx_shift_reg[1]));
   SDFFRHQX2 \u_spi_slave_rx_data_reg[6]  (.CK(clk),
	.D(slave_rx[6]),
	.Q(slave_rx[6]),
	.RN(rst_n),
	.SE(n_36),
	.SI(u_spi_slave_rx_shift_reg[6]));
   SDFFRHQX2 \u_spi_slave_rx_data_reg[5]  (.CK(clk),
	.D(slave_rx[5]),
	.Q(slave_rx[5]),
	.RN(rst_n),
	.SE(n_36),
	.SI(u_spi_slave_rx_shift_reg[5]));
   NOR3X1 g2698__2883 (.A(u_spi_slave_sclk_d1),
	.B(u_spi_slave_cs_n_d2),
	.C(n_12),
	.Y(n_54));
   NAND2XL g2684__2346 (.A(n_28),
	.B(n_32),
	.Y(n_33));
   AND2X1 g2705__1666 (.A(n_31),
	.B(n_32),
	.Y(n_42));
   DFFRHQX2 u_spi_slave_data_valid_reg (.CK(clk),
	.D(n_36),
	.Q(slave_data_valid),
	.RN(rst_n));
   NAND2XL g2701__7410 (.A(n_53),
	.B(slave_tx[7]),
	.Y(n_30));
   SDFFRHQX2 \u_spi_master_rx_data_reg[1]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[1]),
	.Q(master_rx[1]),
	.RN(rst_n),
	.SE(n_29),
	.SI(master_rx[1]));
   SDFFRHQX2 \u_spi_master_rx_data_reg[5]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[5]),
	.Q(master_rx[5]),
	.RN(rst_n),
	.SE(n_29),
	.SI(master_rx[5]));
   NAND2BX1 g2683__6417 (.AN(n_28),
	.B(sclk),
	.Y(n_35));
   SDFFRHQX2 \u_spi_master_rx_data_reg[7]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[7]),
	.Q(master_rx[7]),
	.RN(rst_n),
	.SE(n_29),
	.SI(master_rx[7]));
   NOR2X1 g2686__5477 (.A(sclk),
	.B(n_28),
	.Y(n_41));
   SDFFRHQX2 \u_spi_master_rx_data_reg[3]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[3]),
	.Q(master_rx[3]),
	.RN(rst_n),
	.SE(n_29),
	.SI(master_rx[3]));
   SDFFRHQX2 \u_spi_master_rx_data_reg[2]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[2]),
	.Q(master_rx[2]),
	.RN(rst_n),
	.SE(n_29),
	.SI(master_rx[2]));
   SDFFRHQX2 \u_spi_master_rx_data_reg[6]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[6]),
	.Q(master_rx[6]),
	.RN(rst_n),
	.SE(n_29),
	.SI(master_rx[6]));
   SDFFRHQX2 \u_spi_master_rx_data_reg[0]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[0]),
	.Q(master_rx[0]),
	.RN(rst_n),
	.SE(n_29),
	.SI(master_rx[0]));
   SDFFRHQX2 \u_spi_master_rx_data_reg[4]  (.CK(clk),
	.D(u_spi_master_rx_shift_reg[4]),
	.Q(master_rx[4]),
	.RN(rst_n),
	.SE(n_29),
	.SI(master_rx[4]));
   NOR2XL g2704__2398 (.A(n_53),
	.B(n_36),
	.Y(n_70));
   DFFRHQX1 \u_spi_master_state_reg[1]  (.CK(clk),
	.D(n_10),
	.Q(u_spi_master_state[1]),
	.RN(rst_n));
   AOI211X1 g2702__5107 (.A0(u_spi_master_bit_cnt[0]),
	.A1(u_spi_master_bit_cnt[1]),
	.B0(n_3),
	.C0(n_13),
	.Y(n_27));
   AO22X1 g2710__6260 (.A0(master_tx[2]),
	.A1(n_24),
	.B0(u_spi_master_tx_shift_reg[1]),
	.B1(n_23),
	.Y(n_26));
   AO22X1 g2708__4319 (.A0(master_tx[1]),
	.A1(n_24),
	.B0(u_spi_master_tx_shift_reg[0]),
	.B1(n_23),
	.Y(n_25));
   AO22X1 g2707__8428 (.A0(master_tx[3]),
	.A1(n_24),
	.B0(u_spi_master_tx_shift_reg[2]),
	.B1(n_23),
	.Y(n_22));
   DFFRHQX1 \u_spi_master_div_cnt_reg[1]  (.CK(clk),
	.D(n_9),
	.Q(u_spi_master_div_cnt[1]),
	.RN(rst_n));
   AO22X1 g2711__5526 (.A0(master_tx[6]),
	.A1(n_24),
	.B0(u_spi_master_tx_shift_reg[5]),
	.B1(n_23),
	.Y(n_21));
   AO22X1 g2712__6783 (.A0(master_tx[4]),
	.A1(n_24),
	.B0(u_spi_master_tx_shift_reg[3]),
	.B1(n_23),
	.Y(n_20));
   AO22X1 g2713__3680 (.A0(master_tx[5]),
	.A1(n_24),
	.B0(u_spi_master_tx_shift_reg[4]),
	.B1(n_23),
	.Y(n_19));
   INVXL g2716 (.A(n_38),
	.Y(n_18));
   NOR2XL g2726__1617 (.A(n_17),
	.B(n_24),
	.Y(n_32));
   NOR3BX2 g2714__2802 (.AN(u_spi_slave_sclk_d1),
	.B(u_spi_slave_sclk_d2),
	.C(u_spi_slave_cs_n_d2),
	.Y(n_37));
   DFFRHQX2 u_spi_master_done_reg (.CK(clk),
	.D(n_5),
	.Q(master_done),
	.RN(rst_n));
   OAI2BB1X1 g2693__1705 (.A0N(u_spi_master_bit_cnt[2]),
	.A1N(n_7),
	.B0(n_23),
	.Y(n_16));
   AO22X1 g2709__5122 (.A0(master_tx[7]),
	.A1(n_43),
	.B0(u_spi_master_tx_shift_reg[6]),
	.B1(n_23),
	.Y(n_15));
   NAND4XL g2697__8246 (.A(u_spi_master_div_cnt[0]),
	.B(u_spi_master_sclk_en),
	.C(u_spi_master_div_cnt[1]),
	.D(n_23),
	.Y(n_28));
   NAND2XL g2719__7098 (.A(start),
	.B(n_24),
	.Y(n_38));
   NOR2XL g2724__6131 (.A(sclk),
	.B(n_13),
	.Y(n_14));
   OAI31X1 g2723__1881 (.A0(u_spi_slave_bit_cnt[1]),
	.A1(u_spi_slave_bit_cnt[0]),
	.A2(u_spi_slave_bit_cnt[2]),
	.B0(u_spi_slave_sclk_d2),
	.Y(n_12));
   AND2XL g2722__5115 (.A(master_tx[0]),
	.B(n_24),
	.Y(n_11));
   NAND2XL g2725__7482 (.A(n_31),
	.B(n_13),
	.Y(n_10));
   NOR2BX1 g2721__4733 (.AN(u_spi_slave_cs_n_d2),
	.B(u_spi_slave_cs_n_d1),
	.Y(n_53));
   NOR2BX1 g2727__6161 (.AN(u_spi_slave_cs_n_d1),
	.B(u_spi_slave_cs_n_d2),
	.Y(n_36));
   AND2XL g2699__9315 (.A(u_spi_master_sclk_en),
	.B(n_4),
	.Y(n_9));
   CLKINVX1 g2734 (.A(n_29),
	.Y(n_17));
   NAND2XL g2717__9945 (.A(u_spi_master_bit_cnt[0]),
	.B(n_23),
	.Y(n_8));
   OR2X1 g2703__2883 (.A(u_spi_master_bit_cnt[2]),
	.B(n_7),
	.Y(n_34));
   CLKINVX1 g2732 (.A(n_43),
	.Y(n_31));
   CLKINVX1 g2733 (.A(n_23),
	.Y(n_13));
   NOR2BX1 g2737__2346 (.AN(n_6),
	.B(u_spi_master_state[2]),
	.Y(n_24));
   NAND3X1 g2739__1666 (.A(u_spi_master_state[0]),
	.B(u_spi_master_state[1]),
	.C(n_0),
	.Y(n_29));
   AND2XL g2728__7410 (.A(u_spi_master_state[2]),
	.B(n_6),
	.Y(n_5));
   DFFRHQX1 u_spi_slave_sclk_d2_reg (.CK(clk),
	.D(FE_PHN2_u_spi_slave_sclk_d1),
	.Q(u_spi_slave_sclk_d2),
	.RN(rst_n));
   DFFRHQX1 \u_spi_master_div_cnt_reg[0]  (.CK(clk),
	.D(n_2),
	.Q(u_spi_master_div_cnt[0]),
	.RN(rst_n));
   DFFSHQX1 u_spi_slave_cs_n_d2_reg (.CK(clk),
	.D(FE_PHN1_u_spi_slave_cs_n_d1),
	.Q(u_spi_slave_cs_n_d2),
	.SN(rst_n));
   XOR2XL g2735__6417 (.A(u_spi_master_div_cnt[0]),
	.B(u_spi_master_div_cnt[1]),
	.Y(n_4));
   NOR3BX1 g2736__5477 (.AN(u_spi_master_state[0]),
	.B(u_spi_master_state[2]),
	.C(u_spi_master_state[1]),
	.Y(n_43));
   INVXL g2715 (.A(n_3),
	.Y(n_7));
   NOR3BX1 g2738__2398 (.AN(u_spi_master_state[1]),
	.B(u_spi_master_state[2]),
	.C(u_spi_master_state[0]),
	.Y(n_23));
   NOR2XL g2743__5107 (.A(u_spi_master_bit_cnt[0]),
	.B(u_spi_master_bit_cnt[1]),
	.Y(n_3));
   DFFRHQX1 u_spi_slave_sclk_d1_reg (.CK(clk),
	.D(FE_PHN4_sclk),
	.Q(u_spi_slave_sclk_d1),
	.RN(rst_n));
   NOR2BX1 g2742__6260 (.AN(u_spi_master_sclk_en),
	.B(FE_PHN3_u_spi_master_div_cnt_0),
	.Y(n_2));
   NOR2XL g2744__4319 (.A(u_spi_master_state[0]),
	.B(u_spi_master_state[1]),
	.Y(n_6));
   DFFSHQX1 u_spi_slave_cs_n_d1_reg (.CK(clk),
	.D(FE_PHN0_cs_n),
	.Q(u_spi_slave_cs_n_d1),
	.SN(rst_n));
   CLKINVX1 g2746 (.A(u_spi_slave_bit_cnt[1]),
	.Y(n_61));
   INVXL g2745 (.A(u_spi_master_bit_cnt[1]),
	.Y(n_1));
   DFFRX1 \u_spi_master_state_reg[2]  (.CK(clk),
	.D(n_17),
	.Q(u_spi_master_state[2]),
	.QN(n_0),
	.RN(rst_n));
endmodule

